import { TFile, normalizePath } from "obsidian";
import type { App } from "obsidian";
import { currentReviewRound, loadReviewSession, reviewSessionRootPath, reviewWorkingRootPath, type ReviewDocument, type ReviewParticipant, type ReviewParticipantRole } from "./native-review-session.js";

export interface NativeReviewThreadAnchor { start: number; end: number; quote: string; prefix: string; suffix: string; }
export interface NativeReviewThreadMessage { messageId: string; participantId: string; text: string; createdAt: string; }
export interface NativeReviewThread { threadId: string; documentId: string; anchor: NativeReviewThreadAnchor; createdByParticipantId: string; createdAt: string; status: "open" | "resolved"; resolvedAt?: string; resolvedByParticipantId?: string; messages: NativeReviewThreadMessage[]; }
export interface NativeReviewThreadsStore { version: 1; threads: NativeReviewThread[]; }
export class NativeReviewThreadsError extends Error { constructor(message: string) { super(message); this.name = "NativeReviewThreadsError"; } }

function fail(message: string): never { throw new NativeReviewThreadsError(message); }
function record(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function nonEmpty(value: unknown, label: string): asserts value is string { if (typeof value !== "string" || value.trim() === "") fail(`${label} invalide`); }
function date(value: unknown, label: string): asserts value is string { if (typeof value !== "string" || value.trim() === "" || Number.isNaN(Date.parse(value))) fail(`${label} invalide`); }
function id(value: unknown, prefix: "thread" | "message", label: string): asserts value is string { if (typeof value !== "string" || !new RegExp(`^${prefix}-[a-f0-9]{32}$`).test(value)) fail(`${label} invalide`); }
function participantIds(participants: Array<Pick<ReviewParticipant, "id" | "role">>): Map<string, ReviewParticipantRole> { return new Map(participants.map((participant) => [participant.id, participant.role])); }
function documentIds(documents: Array<Pick<ReviewDocument, "documentId">>): Set<string> { return new Set(documents.map((document) => document.documentId)); }

export function nativeReviewThreadsPath(reviewId: string): string { return normalizePath(`${reviewSessionRootPath(reviewId)}/threads.json`); }
export function validateNativeReviewThreads(value: unknown, participants: Array<Pick<ReviewParticipant, "id" | "role">>, documents: Array<Pick<ReviewDocument, "documentId">>): asserts value is NativeReviewThreadsStore {
  if (!record(value) || value.version !== 1 || !Array.isArray(value.threads)) fail("Store de fils invalide");
  const people = participantIds(participants); const docs = documentIds(documents); const threadIds = new Set<string>(); const messageIds = new Set<string>();
  for (const thread of value.threads) {
    if (!record(thread)) fail("Fil invalide"); id(thread.threadId, "thread", "threadId"); if (threadIds.has(thread.threadId)) fail("threadId dupliqué"); threadIds.add(thread.threadId);
    if (typeof thread.documentId !== "string" || !docs.has(thread.documentId)) fail("documentId de fil invalide");
    if (!record(thread.anchor)) fail("Ancre invalide"); const anchor = thread.anchor; const start = anchor.start; const end = anchor.end;
    if (typeof start !== "number" || typeof end !== "number" || !Number.isSafeInteger(start) || !Number.isSafeInteger(end) || start < 0 || start >= end) fail("Positions d’ancre invalides");
    nonEmpty(anchor.quote, "quote"); if (typeof anchor.prefix !== "string" || typeof anchor.suffix !== "string") fail("Contexte d’ancre invalide");
    if (typeof thread.createdByParticipantId !== "string" || !people.has(thread.createdByParticipantId)) fail("Créateur de fil invalide"); date(thread.createdAt, "createdAt");
    if (thread.status !== "open" && thread.status !== "resolved") fail("Statut de fil invalide");
    if (thread.status === "resolved") { date(thread.resolvedAt, "resolvedAt"); if (typeof thread.resolvedByParticipantId !== "string" || !people.has(thread.resolvedByParticipantId)) fail("resolvedByParticipantId invalide"); }
    else if (thread.resolvedAt !== undefined || thread.resolvedByParticipantId !== undefined) fail("Fil ouvert avec résolution");
    if (!Array.isArray(thread.messages) || thread.messages.length === 0) fail("Messages de fil invalides");
    for (const message of thread.messages) { if (!record(message)) fail("Message invalide"); id(message.messageId, "message", "messageId"); if (messageIds.has(message.messageId)) fail("messageId dupliqué"); messageIds.add(message.messageId); if (typeof message.participantId !== "string" || !people.has(message.participantId)) fail("participantId de message invalide"); nonEmpty(message.text, "Texte de message"); date(message.createdAt, "createdAt de message"); }
  }
}

function exact(value: unknown): string { return JSON.stringify(value); }
export function assertNativeReviewThreadEvolution(previousThreads: NativeReviewThread[], nextThreads: NativeReviewThread[], participants: Array<Pick<ReviewParticipant, "id" | "role">>, documents: Array<Pick<ReviewDocument, "documentId">>, senderRole: ReviewParticipantRole): void {
  validateNativeReviewThreads({ version: 1, threads: previousThreads }, participants, documents); validateNativeReviewThreads({ version: 1, threads: nextThreads }, participants, documents);
  const sender = participants.find((participant) => participant.role === senderRole); if (!sender) fail("Participant émetteur introuvable");
  const previous = new Map(previousThreads.map((thread) => [thread.threadId, thread])); const allIds = new Set<string>();
  for (const thread of previousThreads) { allIds.add(thread.threadId); thread.messages.forEach((message) => allIds.add(message.messageId)); }
  for (const next of nextThreads) {
    const old = previous.get(next.threadId);
    if (!old) { if (next.createdByParticipantId !== sender.id || next.messages.some((message) => message.participantId !== sender.id)) fail("Nouveau fil attribué au mauvais participant"); if (allIds.has(next.threadId)) fail("ID réutilisé"); next.messages.forEach((message) => { if (allIds.has(message.messageId)) fail("ID réutilisé"); allIds.add(message.messageId); }); continue; }
    if (exact({ documentId: old.documentId, anchor: old.anchor, createdByParticipantId: old.createdByParticipantId, createdAt: old.createdAt }) !== exact({ documentId: next.documentId, anchor: next.anchor, createdByParticipantId: next.createdByParticipantId, createdAt: next.createdAt })) fail("Métadonnées historiques modifiées");
    if (next.messages.length < old.messages.length || old.messages.some((message, index) => exact(message) !== exact(next.messages[index]))) fail("Historique de messages modifié");
    for (const message of next.messages.slice(old.messages.length)) { if (message.participantId !== sender.id || allIds.has(message.messageId)) fail("Ajout de message invalide"); allIds.add(message.messageId); }
    if (old.status !== next.status) { if (next.status === "resolved" && (next.resolvedByParticipantId !== sender.id || !next.resolvedAt)) fail("Résolution invalide"); if (next.status === "open" && (next.resolvedAt !== undefined || next.resolvedByParticipantId !== undefined)) fail("Réouverture invalide"); }
    else if (old.resolvedAt !== next.resolvedAt || old.resolvedByParticipantId !== next.resolvedByParticipantId) fail("Résolution historique modifiée");
  }
  for (const old of previousThreads) if (!nextThreads.some((thread) => thread.threadId === old.threadId)) fail("Fil historique supprimé");
}

function fresh(prefix: "thread" | "message"): string { if (typeof crypto === "undefined" || !crypto.getRandomValues) fail("Web Crypto indisponible"); return `${prefix}-${Array.from(crypto.getRandomValues(new Uint8Array(16)), (byte) => byte.toString(16).padStart(2, "0")).join("")}`; }
function active(session: Awaited<ReturnType<typeof loadReviewSession>>, role: ReviewParticipantRole): ReviewParticipant { if (!session || session.status !== "active" || session.localRole !== role) fail("Session ou rôle local invalide"); const round = currentReviewRound(session); if (role === "reviewer" ? !round.received || !!round.sent : !round.sent || !round.received) fail("Ce n’est pas le tour actif du participant"); const participant = session.participants.find((item) => item.role === role); if (!participant) fail("Participant introuvable"); return participant; }
async function store(app: App, reviewId: string, session: NonNullable<Awaited<ReturnType<typeof loadReviewSession>>>): Promise<NativeReviewThreadsStore> { const path = nativeReviewThreadsPath(reviewId); const file = app.vault.getAbstractFileByPath(path); if (!file) return { version: 1, threads: [] }; if (!(file instanceof TFile)) fail("threads.json invalide"); let parsed: unknown; try { parsed = JSON.parse(await app.vault.read(file)); } catch { fail("threads.json corrompu"); } validateNativeReviewThreads(parsed, session.participants, session.documents); return parsed; }
async function persist(app: App, reviewId: string, value: NativeReviewThreadsStore): Promise<void> { const path = nativeReviewThreadsPath(reviewId); const file = app.vault.getAbstractFileByPath(path); if (file instanceof TFile) await app.vault.modify(file, JSON.stringify(value, null, 2)); else if (file) fail("threads.json invalide"); else await app.vault.create(path, JSON.stringify(value, null, 2)); }
export async function loadNativeReviewThreads(app: App, reviewId: string): Promise<NativeReviewThreadsStore> { const session = await loadReviewSession(app, reviewId); if (!session) fail(`Session introuvable : ${reviewId}`); return store(app, reviewId, session); }
export async function addNativeReviewThread(app: App, reviewId: string, documentId: string, start: number, end: number, text: string): Promise<NativeReviewThread> { const session = await loadReviewSession(app, reviewId); const participant = active(session, "reviewer"); const document = session!.documents.find((item) => item.documentId === documentId); const path = normalizePath(`${reviewWorkingRootPath(reviewId)}/${documentId}.md`); if (!document || document.localSourcePath !== path) fail("Document working invalide"); const file = app.vault.getAbstractFileByPath(path); if (!(file instanceof TFile)) fail("Working introuvable"); const markdown = await app.vault.read(file); if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end) || start < 0 || start >= end || end > markdown.length) fail("Sélection invalide"); nonEmpty(text, "Texte de message"); const quote = markdown.slice(start, end); if (!quote) fail("Citation vide"); const now = new Date().toISOString(); const thread: NativeReviewThread = { threadId: fresh("thread"), documentId, anchor: { start, end, quote, prefix: markdown.slice(Math.max(0, start - 64), start), suffix: markdown.slice(end, end + 64) }, createdByParticipantId: participant.id, createdAt: now, status: "open", messages: [{ messageId: fresh("message"), participantId: participant.id, text, createdAt: now }] }; const value = await store(app, reviewId, session!); assertNativeReviewThreadEvolution(value.threads, [...value.threads, thread], session!.participants, session!.documents, "reviewer"); value.threads.push(thread); await persist(app, reviewId, value); return thread; }
export async function replyNativeReviewThread(app: App, reviewId: string, threadId: string, text: string): Promise<void> { const session = await loadReviewSession(app, reviewId); if (!session) fail(`Session introuvable : ${reviewId}`); const participant = active(session, session.localRole); nonEmpty(text, "Texte de message"); const value = await store(app, reviewId, session); const thread = value.threads.find((item) => item.threadId === threadId); if (!thread) fail("Fil introuvable"); const next = JSON.parse(JSON.stringify(value.threads)) as NativeReviewThread[]; next.find((item) => item.threadId === threadId)!.messages.push({ messageId: fresh("message"), participantId: participant.id, text, createdAt: new Date().toISOString() }); assertNativeReviewThreadEvolution(value.threads, next, session.participants, session.documents, session.localRole); value.threads = next; await persist(app, reviewId, value); }
export async function setNativeReviewThreadResolved(app: App, reviewId: string, threadId: string, resolved: boolean): Promise<void> { const session = await loadReviewSession(app, reviewId); if (!session) fail(`Session introuvable : ${reviewId}`); const participant = active(session, session.localRole); if (typeof resolved !== "boolean") fail("Résolution invalide"); const value = await store(app, reviewId, session); const next = JSON.parse(JSON.stringify(value.threads)) as NativeReviewThread[]; const thread = next.find((item) => item.threadId === threadId); if (!thread) fail("Fil introuvable"); thread.status = resolved ? "resolved" : "open"; if (resolved) { thread.resolvedAt = new Date().toISOString(); thread.resolvedByParticipantId = participant.id; } else { delete thread.resolvedAt; delete thread.resolvedByParticipantId; } assertNativeReviewThreadEvolution(value.threads, next, session.participants, session.documents, session.localRole); value.threads = next; await persist(app, reviewId, value); }
