import { Menu, setIcon } from "obsidian";
import { addOutlinerItem, findPlanItem, indentPlanItem, movePlanItem, outdentPlanItem, removeNewOutlinerItem, type BinderOutlinerItem } from "../services/canvas-binder-plan.js";

type OutlinerNode = { contentEl?: HTMLElement; getData?: () => Record<string, unknown>; setData?: (data: Record<string, unknown>) => void; canvas?: { requestSave?: () => void } };
const stop = (event: Event) => event.stopPropagation();
export function renderBinderPlanOutliner(node: OutlinerNode): void {
  const host = node.contentEl; const data = node.getData?.(); if (!host || !data || !Array.isArray(data.feuillets_binder_items)) return;
  host.empty(); host.addClass("feuillets-binder-plan-node"); const root = host.createDiv({ cls: "feuillets-plan-outliner" }); const header = root.createDiv({ cls: "feuillets-plan-header" }); header.createSpan({ text: "Plan du manuscrit" }); if (data.feuillets_binder_dirty) header.createSpan({ cls: "feuillets-plan-dirty", text: "•" }); const actions = header.createDiv({ cls: "feuillets-plan-actions" });
  const save = (items: BinderOutlinerItem[], focus?: string) => { node.setData?.({ ...data, feuillets_binder_items: items, feuillets_binder_dirty: true, feuillets_binder_focus: focus }); node.canvas?.requestSave?.(); };
  const iconButton = (icon: string, label: string, action: () => void) => { const button = actions.createEl("button", { attr: { "aria-label": label } }); setIcon(button, icon); button.addEventListener("pointerdown", stop); button.addEventListener("click", (event) => { stop(event); action(); }); return button; };
  iconButton("refresh-cw", "Actualiser depuis le Binder", () => {}); iconButton("plus", "Ajouter", () => { const menu = new Menu(); menu.addItem((item) => item.setTitle("Nouveau feuillet").setIcon("file-plus").onClick(() => save(addOutlinerItem(data.feuillets_binder_items as BinderOutlinerItem[], "new-file")))); menu.addItem((item) => item.setTitle("Nouveau dossier").setIcon("folder-plus").onClick(() => save(addOutlinerItem(data.feuillets_binder_items as BinderOutlinerItem[], "new-folder")))); menu.showAtMouseEvent(new MouseEvent("click")); }); const apply = iconButton("check", "Appliquer au Binder", () => {}); apply.disabled = data.feuillets_binder_dirty !== true;
  const tree = root.createDiv({ cls: "feuillets-plan-tree-scroll" }); let selected = typeof data.feuillets_binder_focus === "string" ? data.feuillets_binder_focus : ""; let drag: { id: string; x: number; y: number; active: boolean; target?: string; position?: "before" | "after" | "inside" } | null = null;
  const clearDrop = () => tree.querySelectorAll(".is-dragging,.drop-before,.drop-after,.drop-inside").forEach((element) => element.removeClass("is-dragging", "drop-before", "drop-after", "drop-inside"));
  const updateDrop = (event: PointerEvent) => { if (!drag) return; const source = findPlanItem(data.feuillets_binder_items as BinderOutlinerItem[], drag.id); const rows = Array.from(tree.querySelectorAll<HTMLElement>(".feuillets-plan-row")).filter((row) => { const item = findPlanItem(data.feuillets_binder_items as BinderOutlinerItem[], row.dataset.planId || ""); return !!item && !source?.children.some((child) => child.id === item.id) && item.id !== drag?.id; }); if (!rows.length) return; const targetRow = rows.reduce((best, row) => Math.abs(row.getBoundingClientRect().top + row.getBoundingClientRect().height / 2 - event.clientY) < Math.abs(best.getBoundingClientRect().top + best.getBoundingClientRect().height / 2 - event.clientY) ? row : best); const target = findPlanItem(data.feuillets_binder_items as BinderOutlinerItem[], targetRow.dataset.planId || ""); if (!target) return; const rect = targetRow.getBoundingClientRect(); const central = event.clientY > rect.top + rect.height * .3 && event.clientY < rect.bottom - rect.height * .3; const position = target.kind.endsWith("folder") && (central || event.clientX > rect.left + 42) ? "inside" : event.clientY < rect.top + rect.height / 2 ? "before" : "after"; clearDrop(); targetRow.addClass(`drop-${position}`); drag.target = target.id; drag.position = position; const bounds = tree.getBoundingClientRect(); if (event.clientY < bounds.top + 32) tree.scrollTop -= 12; if (event.clientY > bounds.bottom - 32) tree.scrollTop += 12; };
  const draw = (items: BinderOutlinerItem[], depth: number) => items.forEach((item) => { const row = tree.createDiv({ cls: `feuillets-plan-row${selected === item.id ? " is-selected" : ""}` }); row.dataset.planId = item.id; row.tabIndex = 0; row.style.paddingLeft = `${depth * 19}px`; row.addEventListener("pointerdown", stop); row.addEventListener("dblclick", stop); row.addEventListener("click", (event) => { stop(event); selected = item.id; row.addClass("is-selected"); }); row.addEventListener("keydown", (event) => { stop(event); if (event.key === "Enter") save(addOutlinerItem(items, event.metaKey || event.ctrlKey ? "new-folder" : "new-file"), item.id); else if (event.key === "Tab") { event.preventDefault(); save(event.shiftKey ? outdentPlanItem(data.feuillets_binder_items as BinderOutlinerItem[], item.id) : indentPlanItem(data.feuillets_binder_items as BinderOutlinerItem[], item.id), item.id); } else if ((event.key === "Backspace" || event.key === "Delete") && item.kind.startsWith("new-") && !item.title) save(removeNewOutlinerItem(data.feuillets_binder_items as BinderOutlinerItem[], item.id)); });
    const grip = row.createSpan({ cls: "feuillets-plan-grip" }); setIcon(grip, "grip-vertical"); grip.addEventListener("pointerdown", (event) => { event.preventDefault(); stop(event); grip.setPointerCapture(event.pointerId); drag = { id: item.id, x: event.clientX, y: event.clientY, active: false }; }); grip.addEventListener("pointermove", (event) => { if (!drag) return; stop(event); if (!drag.active && Math.hypot(event.clientX - drag.x, event.clientY - drag.y) > 4) { drag.active = true; row.addClass("is-dragging"); } if (drag.active) updateDrop(event); }); const finish = (event: PointerEvent) => { stop(event); if (drag?.active && drag.target && drag.position) { const next = movePlanItem(data.feuillets_binder_items as BinderOutlinerItem[], drag.id, drag.target, drag.position); if (next !== data.feuillets_binder_items) save(next, drag.id); } clearDrop(); drag = null; }; grip.addEventListener("pointerup", finish); grip.addEventListener("pointercancel", finish); if (item.kind.endsWith("folder")) { const toggle = row.createEl("button", { cls: "feuillets-plan-toggle" }); setIcon(toggle, item.collapsed ? "chevron-right" : "chevron-down"); toggle.addEventListener("click", (event) => { stop(event); item.collapsed = !item.collapsed; save(data.feuillets_binder_items as BinderOutlinerItem[], item.id); }); } else row.createSpan({ cls: "feuillets-plan-toggle-space" }); const icon = row.createSpan({ cls: "feuillets-plan-kind" }); setIcon(icon, item.kind.endsWith("folder") ? "folder" : "file-text"); if (item.kind.startsWith("new-")) { const input = row.createEl("input", { value: item.title, placeholder: "Titre" }); input.addEventListener("input", () => { item.title = input.value; save(data.feuillets_binder_items as BinderOutlinerItem[], item.id); }); } else row.createSpan({ cls: "feuillets-plan-title", text: item.title }); if (!item.collapsed) draw(item.children, depth + 1); });
  tree.addEventListener("pointerdown", stop); tree.addEventListener("mousedown", stop); tree.addEventListener("click", stop); tree.addEventListener("dblclick", stop); tree.addEventListener("wheel", (event) => { if (!event.ctrlKey && !event.metaKey) stop(event); }); root.addEventListener("keydown", stop); draw(data.feuillets_binder_items as BinderOutlinerItem[], 0);
}
