export type GenealogyPerson={id:string;name:string;dates?:string};
export type ParentChildRelation={childId:string;type:"biological"|"adoptive"};
export type GenealogyFamily={id:string;partners:string[];unionType:"normal"|"special";children:ParentChildRelation[];line:number};
export type GenealogyError={line:number;message:string};
export type GenealogyDocument={people:GenealogyPerson[];families:GenealogyFamily[];errors:GenealogyError[]};
const split=(s:string,d:string):string[]=>{const out:string[]=[];let start=0,depth=0;for(let i=0;i<s.length;i+=1){if(s[i]==="[")depth+=1;else if(s[i]==="]")depth=Math.max(0,depth-1);else if(s[i]===d&&depth===0){out.push(s.slice(start,i));start=i+1;}}out.push(s.slice(start));return out;};
const relation=(s:string):{left:string;right:string;adoptive:boolean}|undefined=>{let depth=0;for(let i=0;i<s.length-1;i+=1){if(s[i]==="[")depth+=1;else if(s[i]==="]")depth=Math.max(0,depth-1);else if(depth===0&&((s[i]==="-"||s[i]==="=")&&s[i+1]===">")){return {left:s.slice(0,i),right:s.slice(i+2),adoptive:s[i]==="="};}}return undefined;};
const person=(s:string):{name:string;dates?:string}|undefined=>{const t=s.trim();if(!t||t.includes("|"))return undefined;const i=t.indexOf("[");if(i<0)return {name:t};if(!t.endsWith("]"))return undefined;const name=t.slice(0,i).trim(),dates=t.slice(i+1,-1).trim();return name?(dates?{name,dates}:{name}):undefined;};
export function parseGenealogy(source:string):GenealogyDocument{const people=new Map<string,GenealogyPerson>(),families:GenealogyFamily[]=[],errors:GenealogyError[]=[];let unknown=0;const ensure=(p:{name:string;dates?:string},id=p.name):string=>{const old=people.get(id);if(!old)people.set(id,{id,name:p.name,...(p.dates?{dates:p.dates}:{})});else if(!old.dates&&p.dates)old.dates=p.dates;return id;};source.split(/\r?\n/).forEach((raw,index)=>{const line=index+1,v=raw.trim();if(!v)return;const r=relation(v);if(!r){const u=split(v,v.includes("~")?"~":"+");if(u.length===2){const ps=u.map(person);if(ps.every((x):x is {name:string;dates?:string}=>!!x)){families.push({id:`family-${line}-${families.length}`,partners:ps.map(p=>ensure(p,p.name==="?"?`?${++unknown}`:p.name)),unionType:v.includes("~")?"special":"normal",children:[],line});return;}}const p=person(v);if(p)ensure(p,p.name==="?"?`?${++unknown}`:p.name);else errors.push({line,message:"déclaration de personne invalide"});return;}const parts=split(r.left,r.left.includes("~")?"~":"+"),ps=parts.map(person),cs=split(r.right,",").map(person);if(parts.length<1||parts.length>2||cs.length===0||ps.some(p=>!p)||cs.some(c=>!c)){errors.push({line,message:"parents ou enfants invalides"});return;}const ids=ps.map(p=>ensure(p as {name:string;dates?:string},p?.name==="?"?`?${++unknown}`:p?.name||""));const children=cs.map(c=>ensure(c as {name:string;dates?:string},c?.name==="?"?`?${++unknown}`:c?.name||""));families.push({id:`family-${line}-${families.length}`,partners:ids,unionType:r.left.includes("~")?"special":"normal",children:children.map(childId=>({childId,type:r.adoptive?"adoptive":"biological"})),line});});const graph=new Map<string,string[]>();for(const f of families)for(const p of f.partners)graph.set(p,[...(graph.get(p)||[]),...f.children.map(c=>c.childId)]);const visiting=new Set<string>(),visited=new Set<string>();const visit=(id:string):boolean=>{if(visiting.has(id))return true;if(visited.has(id))return false;visiting.add(id);if((graph.get(id)||[]).some(visit))return true;visiting.delete(id);visited.add(id);return false;};if([...people.keys()].some(visit))errors.push({line:1,message:"cycle généalogique détecté"});return {people:[...people.values()].sort((a,b)=>a.name.localeCompare(b.name)),families,errors};}
